variables:    

  # Пути к используемым инструментам
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe'
  NUGET_PATH: 'D:\Distrib\NuGet\nuget.exe'
  DOXYGEN_PATH: 'D:\Distrib\Doxygen\bin\doxygen.exe'
  JFROG_PATH: 'D:\Distrib\jf.exe'
  TEST_UTIL_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'

#default:
#  before_script:
#    - CHCP 65001

# Повторно используемая секция для этапов, которые выполняются при изменениях в транк-ветках
.only_trunk_branches:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH == "develop"
      - $CI_COMMIT_BRANCH == "master"
      - $DEPLOY

# Перечень этапов 
stages:
  - build
  - docs
  - deploy

# ----------------- Сборка проекта ----------------- 
build-job:
  stage: build
  only:
  script:    
    # restore Nuget dependencies
    - echo "Restore Nuget"
    - '& "$env:NUGET_PATH" restore'  

    # define minor build version units
    - echo "Define Version"
    - Set-Variable -Name "BUILD_NUMBER" -Value (Get-Date -Format "MMdd")
    - Set-Variable -Name "REVISION_NUMBER" -Value (Get-Date -Format "HHmm")

    # build solution 
    - echo "Compile sources"
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /p:Platform=x64 /p:BuildVersion="$BUILD_NUMBER" /p:RevisionNumber="$REVISION_NUMBER" /p:RevisionId="$env:CI_COMMIT_SHORT_SHA" /p:DefineConstants="CI_BUILD"'   
  artifacts:
    expire_in: 1 day
    untracked: true

# ---------------- Создание Doxygen-документации ----------------- 
# Doxygen должен быть установлен в системе
# Создаётся два комплекста документации :
# - полный (docs-full) (потом будет размещён отдельным архивом)
# - обзорный (docs-brief) (потом будет включён в инсталлер)
docs_job:
  extends: .only_trunk_branches
  stage: docs
  script:   
      
    # Формирование документации
    - '& "$env:DOXYGEN_PATH" docs\doxyfile'
    - mkdir docs\docs-full
    - move docs\html-full docs\docs-full\html
    - xcopy /y /e /i docs\include\* docs\docs-full\include
  artifacts:
    when: always
    expire_in: 1 day
    untracked: true
    paths:
      - 'docs\docs-full\'    

