//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhpdSynchroService.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommandAfterOutput
        {
            get
            {
                return ((bool)(this["CommandAfterOutput"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisconnectError
        {
            get
            {
                return ((bool)(this["DisconnectError"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Verbose
        {
            get
            {
                return ((bool)(this["Verbose"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CDC01-PEINTKT01")]
        public string ZabbixServer
        {
            get
            {
                return ((string)(this["ZabbixServer"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.24.5.65")]
        public string ZabbixUlr
        {
            get
            {
                return ((string)(this["ZabbixUlr"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10051")]
        public int ZabbixPort
        {
            get
            {
                return ((int)(this["ZabbixPort"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=cdc01-pisqlkt01;Initial Catalog=Khpd;User ID=sa;Password=P@ssw0rd")]
        public string SQLConnStr
        {
            get
            {
                return ((string)(this["SQLConnStr"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SSFR_Hist")]
        public string SqlTableToInsert
        {
            get
            {
                return ((string)(this["SqlTableToInsert"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SSFR_Type")]
        public string SqlTypeTableCreate
        {
            get
            {
                return ((string)(this["SqlTypeTableCreate"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config.csv")]
        public string CnfgPath
        {
            get
            {
                return ((string)(this["CnfgPath"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          {
          ConnectionStateSource: ""ConnectionStateSource"",
          ConnectionStateDest :""ConnectionStateDest"",
          ProcessingTime : ""ProcessingTime"",
          TimeStampFileSource : ""TimeStampFileSource"",
          TimeStampFileDest : ""TimeStampFileDest"",
          CntFileSource : ""CntFileSource"",
          CntFileProcessed : ""CntFileProcessed"",
          LiveCounter : ""LiveCounter""
          }
        ")]
        public string Metric
        {
            get
            {
                return ((string)(this["Metric"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ConnectionTime
        {
            get
            {
                return ((int)(this["ConnectionTime"]));
            }
        }

    }
}
